//Всплывашие подсказки как в контакте на чистом js
//Автор: artquant
//Использование: не для коммерции

function artNF(f,c,d,g,l){var a=document.getElementById("nftitle"),k;void 0!=a&&a.parentNode.removeChild(a);a=document.createElement("div");a.id="nftitle";""!=d&&"top"==g?a.innerHTML='<div id="nftitle-title">'+d+'</div><div id="nftitle-body">'+c+'</div><div id="nftitle-arrow-out"><div id="nftitle-arrow-in"></div></div>':"top"==g?a.innerHTML='<div id="nftitle-body">'+c+'</div><div id="nftitle-arrow-out"><div id="nftitle-arrow-in"></div></div>':""!=d&&"bottom"==g?a.innerHTML='<div id="nftitle-arrow-out"><div id="nftitle-arrow-in"></div></div><div id="nftitle-body">'+
c+'</div><div id="nftitle-title">'+d+"</div>":"bottom"==g&&(a.innerHTML='<div id="nftitle-body">'+c+'</div><div id="nftitle-arrow-out"><div id="nftitle-arrow-in"></div></div>');document.body.appendChild(a);var b=document.getElementById("nftitle"),m=document.getElementById("nftitle-body");c=document.getElementById("nftitle-title");d=document.getElementById("nftitle-arrow-out");a=document.getElementById("nftitle-arrow-in");b.style.border="1px solid #ADBAC7";b.style.fontFamily="Tahoma";b.style.fontSize=
"11px";b.style.color="#000000";b.style.position="absolute";b.style.display="inline-block";b.style.background="#ffffff";b.style.boxShadow="0 0 2px rgba(0,0,0,0.2)";b.style.zIndex=99997;b.style.opacity=0;m.style.padding="5px";void 0!=document.getElementById("nftitle-title")&&(c.style.background="#f2f2f2",c.style.padding="5px",c.style.fontWeight="bold");d.style.position="absolute";d.style.zIndex=99998;d.style.border="6px solid transparent";a.style.border="5px solid transparent";a.style.position="absolute";
a.style.zIndex=99999;switch(g){case "top":var e=0.1,h=0;b.style.top=parseInt(document.getElementById(f).offsetTop-document.getElementById("nftitle").offsetHeight-6)-15+"px";b.style.left=parseInt(document.getElementById(f).offsetLeft)-10+"px";void 0!=document.getElementById("nftitle-title")&&(c.style.borderBottom="1px solid #cfd4e5");a.style.borderTop="5px solid #ffffff";a.style.bottom="-3px";a.style.left="-5px";d.style.borderTop="6px solid #ADBAC7";d.style.top=parseInt(b.offsetHeight)-1+"px";d.style.left=
parseInt(document.getElementById(f).offsetWidth/2-6+10)+"px";1>e&&(k=setInterval(function(){e+=0.1;10<=h?clearInterval(k):(b.style.opacity=e,h++,void 0!=document.getElementById("nftitle")&&(b.style.top=parseInt(document.getElementById("nftitle").offsetTop)+1+"px"))},25));break;case "bottom":e=0.1,h=10,g=15,void 0!=document.getElementById("nftitle-title")&&(c.style.borderTop="1px solid #cfd4e5",g=0),b.style.top=parseInt(document.getElementById(f).offsetTop+document.getElementById("nftitle").offsetHeight/
2+6)+g+"px",b.style.left=parseInt(document.getElementById(f).offsetLeft)-10+"px",a.style.borderBottom="5px solid #ffffff",a.style.top="-3px",a.style.left="-5px",d.style.borderBottom="6px solid #ADBAC7",d.style.top="-12px",d.style.left=parseInt(document.getElementById(f).offsetWidth/2-6+10)+"px",1>e&&(k=setInterval(function(){e+=0.1;0>=h?clearInterval(k):(b.style.opacity=e,h--,void 0!=document.getElementById("nftitle")&&(b.style.top=parseInt(document.getElementById("nftitle").offsetTop)-1+"px"))},
25))}l?document.onclick=function(a){for(var b=document.getElementById("nftitle-body").childNodes,d=[],c=0;c<b.length;c++)d.push(b[c]);for(c=0;c<d.length;c++)if(a.target==d[c])return;"undefined"!=document.getElementById("nftitle")&&document.getElementById("nftitle").parentNode.removeChild(document.getElementById("nftitle"))}:null!=document.getElementById(f)&&(document.getElementById(f).onmouseout=function(){document.getElementById("nftitle").parentNode.removeChild(document.getElementById("nftitle"))})}
